describe('Page content', () => {
  it('shows correct content', () => {
    cy.visit('https://coloradohutandyurtfinder.firebaseapp.com/#/')

    cy
      .get('div.btn__content')
      .eq(2)
      .click()
      .url()
      .should('contain', '/createhut')

    cy.get('[aria-label="Hut Name"]').type('Galvanize Platte')

    cy.get('[aria-label="Elevation"]').type('5280')
    cy.get('[aria-label="Trailhead_Elevation"]').type('5280')
    cy.get('[aria-label="Elevation_Gain_From_Trailhead"]').type('0')
    cy.get('[aria-label="Longitude"]').type('39.757888')
    cy.get('[aria-label="Latitude"]').type('-105.006975')
    cy.get('[aria-label="Distance_From_Trailhead"]').type('0')
    cy.get('[aria-label="Distance_From_Nearest_Hut"]').type('0.1')
    cy.get('[aria-label="Contact_Number"]').type('(303)749-0110')
    cy.get('[aria-label="Description"]').type('Galvanize campuses are home to an eclectic mix of entrepreneurs, skilled programmers, expert data scientists, and men and women motivated to make an impact. As different and diverse as we all are, we’re united by common values.')
    cy.get('[aria-label="Booking_Url"]').type('http://www.galvanize.com/')
    cy.get('.input-group--selection-controls__ripple').should('have.length.gt', 8)
    cy.get('.input-group--selection-controls__ripple').eq(0).click()
    cy.get('.input-group--selection-controls__ripple').eq(1).click()
    cy.get('.input-group--selection-controls__ripple').eq(2).click()
    cy.get('.input-group--selection-controls__ripple').eq(3).click()
    cy.get('.input-group--selection-controls__ripple').eq(4).click()
    cy.get('.input-group--selection-controls__ripple').eq(5).click()
    cy.get('.input-group--selection-controls__ripple').eq(6).click()
    cy.get('.input-group--selection-controls__ripple').eq(7).click()
    cy.get('.input-group--selection-controls__ripple').eq(8).click()
    cy.get('.input-group--selection-controls__ripple').eq(9).click()
    cy.get('div').contains('submit').click()
  })
})
